FROM jenkins/inbound-agent:latest
USER root
RUN apt-get update && apt-get install -y docker.io git curl && usermod -aG docker jenkins && apt-get clean
CMD dockerd & java -jar /usr/share/jenkins/agent.jar
