apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--dockerfile=Dockerfile"
            - "--context=git://github.com/sd-sredevops/sre/enterprise-ci-cd.git"
            - "--destination=123456789012.dkr.ecr.us-west-2.amazonaws.com/sd-enterprise-ci-cd:latest"
          env:
            - name: DOCKER_CONFIG
              value: /kaniko/.docker/
          volumeMounts:
            - name: docker-config
              mountPath: /kaniko/.docker/
      restartPolicy: Never
      volumes:
        - name: docker-config
          secret:
            secretName: regcred
